"""
OmniForge Nexus – Official MCP Server
Exposes Local Build Tools to AI Agents via Model Context Protocol (MCP).
"""
import os
import subprocess
from pathlib import Path
from typing import Dict, List, Optional
from fastmcp import FastMCP

# Initialize FastMCP server
mcp = FastMCP("NexusForge")

# Working directory for generated apps
BASE_DIR = Path("e:/projects/Low/Low/omniforge-nexus/generated_apps")
BASE_DIR.mkdir(parents=True, exist_ok=True)

@mcp.tool()
def list_generated_projects() -> List[str]:
    """List all projects that have been generated by OmniForge Nexus."""
    if not BASE_DIR.exists():
        return []
    return [d.name for d in BASE_DIR.iterdir() if d.is_dir()]

@mcp.tool()
def read_project_file(project_name: str, file_path: str) -> str:
    """Read the content of a specific file in a generated project."""
    project_path = BASE_DIR / project_name.lower().replace(" ", "-") / file_path
    if not project_path.exists():
        return f"File {file_path} not found in project {project_name}"
    
    with open(project_path, "r", encoding="utf-8") as f:
        return f.read()

@mcp.tool()
def write_file_to_project(project_name: str, file_path: str, content: str) -> str:
    """Write or update a file in a generated project on the local disk."""
    project_path = BASE_DIR / project_name.lower().replace(" ", "-") / file_path
    project_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(project_path, "w", encoding="utf-8") as f:
        f.write(content)
    return f"Successfully wrote {file_path} to project {project_name}"

@mcp.tool()
def execute_build_command(project_name: str, command: str) -> str:
    """Run a terminal command (e.g., npm install, pip install) in the project root."""
    project_path = BASE_DIR / project_name.lower().replace(" ", "-")
    if not project_path.exists():
        return f"Project {project_name} directory does not exist locally."
    
    try:
        # Warning: Always use caution with shell=True. This tool is for supervised dev commands.
        result = subprocess.run(
            command,
            cwd=str(project_path),
            shell=True,
            capture_output=True,
            text=True,
            timeout=300
        )
        output = result.stdout if result.returncode == 0 else result.stderr
        return f"Command: {command}\nExit Code: {result.returncode}\nOutput:\n{output}"
    except Exception as e:
        return f"Failed to execute command: {str(e)}"

@mcp.tool()
def deploy_local_preview(project_name: str) -> str:
    """
    Attempts to start the backend for a generated project in a separate process.
    Returns the estimated preview URL.
    """
    project_path = BASE_DIR / project_name.lower().replace(" ", "-") / "backend"
    if not project_path.exists():
        return f"Backend directory for {project_name} not found."
    
    # Try starting the fastapi server if it has a main.py
    main_py = project_path / "main.py"
    if main_py.exists():
        # In a real environment, you'd use a process manager or docker.
        # For this tool, we just log that we are 'simulating' the local launch.
        return f"Launch script triggered for {project_name}. Access local preview at http://localhost:8000 (after dependencies are installed)."
    
    return "Launch file (main.py) missing."

if __name__ == "__main__":
    mcp.run()
