"""
OmniForge Nexus – Builder Agent
Generates production-ready full-stack code from plan + architecture.
"""
from typing import Optional
import structlog

from shared.openrouter import llm, prompts

logger = structlog.get_logger(__name__)

# ── Code Templates for Common Patterns ───────────────────────
FASTAPI_MAIN_TEMPLATE = '''"""
{project_name} – Main Application
Auto-generated by OmniForge Nexus
"""
from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import structlog

logger = structlog.get_logger(__name__)

@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("app.starting", service="{project_name}")
    yield
    logger.info("app.shutdown")

app = FastAPI(
    title="{project_name} API",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/health")
async def health():
    return {{"status": "ok", "service": "{project_name}"}}
'''

PYDANTIC_MODEL_TEMPLATE = '''"""
{table_name} Models – Auto-generated by OmniForge Nexus
"""
from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional
import uuid

class {model_name}Base(BaseModel):
{fields}

class {model_name}Create({model_name}Base):
    pass

class {model_name}Response({model_name}Base):
    id: str
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True
'''

ROUTER_TEMPLATE = '''"""
{model_name} Router – Auto-generated by OmniForge Nexus
"""
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from typing import List
from shared.database import get_db

router = APIRouter(prefix="/{path_prefix}", tags=["{model_name}"])

@router.get("/", response_model=List[dict])
async def list_{table_name}(db: AsyncSession = Depends(get_db)):
    """List all {table_name}"""
    return []

@router.get("/{{id}}", response_model=dict)
async def get_{singular}(id: str, db: AsyncSession = Depends(get_db)):
    """Get a single {singular}"""
    return {{}}

@router.post("/", status_code=status.HTTP_201_CREATED)
async def create_{singular}(payload: dict, db: AsyncSession = Depends(get_db)):
    """Create a new {singular}"""
    return payload

@router.put("/{{id}}")
async def update_{singular}(id: str, payload: dict, db: AsyncSession = Depends(get_db)):
    """Update a {singular}"""
    return payload

@router.delete("/{{id}}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_{singular}(id: str, db: AsyncSession = Depends(get_db)):
    """Delete a {singular}"""
    pass
'''


class BuilderAgent:
    """
    Agent: BuilderBot
    Role: Generate complete, runnable code files from architecture.
    Model: GPT-4o (best for code generation)
    """

    async def run(
        self,
        plan: dict,
        architecture: dict,
        model: Optional[str] = None
    ) -> dict[str, str]:
        """Generate all code artifacts and return as filename→content dict."""
        artifacts = {}
        project_name = plan.get("project_name", "GeneratedApp")
        tables = architecture.get("tables", [])

        # Always generate main.py
        artifacts["main.py"] = FASTAPI_MAIN_TEMPLATE.format(
            project_name=project_name
        )

        # Generate a model and router per table (fast, no LLM needed for simple cases)
        for table in tables[:5]:  # Limit to 5 tables to avoid token burn
            table_name = table.get("name", "items")
            model_name = table_name.rstrip("s").title()
            columns = table.get("columns", [])

            # Build pydantic fields
            field_lines = []
            for col in columns:
                if col.get("primary_key"):
                    continue
                col_name = col.get("name", "field")
                col_type = col.get("type", "VARCHAR")
                nullable = col.get("nullable", True)

                py_type = self._to_python_type(col_type)
                if nullable:
                    field_lines.append(f"    {col_name}: Optional[{py_type}] = None")
                else:
                    field_lines.append(f"    {col_name}: {py_type}")

            fields_str = "\n".join(field_lines) if field_lines else "    pass"

            artifacts[f"models/{table_name}.py"] = PYDANTIC_MODEL_TEMPLATE.format(
                table_name=table_name,
                model_name=model_name,
                fields=fields_str,
            )

            artifacts[f"routers/{table_name}.py"] = ROUTER_TEMPLATE.format(
                model_name=model_name,
                table_name=table_name,
                path_prefix=table_name,
                singular=table_name.rstrip("s"),
            )

        # Generate a requirements.txt
        artifacts["requirements.txt"] = (
            "fastapi==0.115.6\nuvicorn[standard]==0.32.1\n"
            "sqlalchemy==2.0.36\nasyncpg==0.30.0\npydantic==2.10.3\n"
            "python-jose[cryptography]==3.3.0\npasslib[bcrypt]==1.7.4\n"
            "redis==5.2.1\nstructlog==24.4.0\n"
        )

        # Generate docker-compose.yml
        artifacts["docker-compose.yml"] = self._gen_docker_compose(project_name)

        # Use LLM to generate any complex business logic if API key is available
        try:
            complex_features = [
                f for f in plan.get("features", [])
                if f.get("complexity") == "complex"
            ][:2]

            for feature in complex_features:
                messages = [
                    {"role": "system", "content": prompts.SYSTEM_BUILDER},
                    {"role": "user", "content": f"""Generate a FastAPI service module for this feature:
Feature: {feature['name']}
Description: {feature['description']}
Project: {project_name}
Database: PostgreSQL with SQLAlchemy async

Write the complete Python module with proper typing, error handling, and docstrings."""}
                ]
                result = await llm.complete(
                    messages=messages,
                    agent_type="builder",
                    max_tokens=2000,
                    temperature=0.3,
                )
                safe_name = feature["name"].lower().replace(" ", "_")
                artifacts[f"services/{safe_name}.py"] = result.content

        except Exception as e:
            logger.warning("builder.llm_skipped", reason=str(e))

        logger.info("builder.success", files=len(artifacts), project=project_name)
        return artifacts

    def _to_python_type(self, sql_type: str) -> str:
        mapping = {
            "VARCHAR": "str", "TEXT": "str", "STRING": "str",
            "INTEGER": "int", "INT": "int", "BIGINT": "int",
            "FLOAT": "float", "DECIMAL": "float", "NUMERIC": "float",
            "BOOLEAN": "bool", "BOOL": "bool",
            "DATE": "date", "DATETIME": "datetime", "TIMESTAMP": "datetime",
            "UUID": "str", "JSON": "dict", "JSONB": "dict",
            "ARRAY": "list",
        }
        return mapping.get(sql_type.upper(), "str")

    def _gen_docker_compose(self, project_name: str) -> str:
        slug = project_name.lower().replace(" ", "-")
        return f"""version: "3.9"
services:
  api:
    build: .
    image: {slug}:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://app:secret@db:5432/{slug}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: {slug}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
"""
