"""
OmniForge Nexus – GitHub Integration Router
Handles GitHub OAuth, repo creation, code push, and GitHub Pages/Actions deployment.
"""
import base64
import json
from typing import Optional
from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import RedirectResponse
from pydantic import BaseModel
import httpx
import structlog

from shared.config import settings

router = APIRouter()
logger = structlog.get_logger(__name__)

GITHUB_API = "https://api.github.com"


# ── Request/Response Models ──────────────────────────────────────

class GitHubTokenRequest(BaseModel):
    token: str  # Personal Access Token


class PushCodeRequest(BaseModel):
    github_token: str
    repo_name: str
    files: dict[str, str]  # filename → content
    description: Optional[str] = "Generated by OmniForge Nexus"
    private: bool = False


class CreateRepoRequest(BaseModel):
    github_token: str
    repo_name: str
    description: Optional[str] = "Generated by OmniForge Nexus"
    private: bool = False
    auto_init: bool = True


class DeployRequest(BaseModel):
    github_token: str
    repo_name: str
    branch: str = "main"


# ── Helpers ──────────────────────────────────────────────────────

async def github_get(endpoint: str, token: str) -> dict:
    """Make an authenticated GET request to GitHub API."""
    async with httpx.AsyncClient() as client:
        resp = await client.get(
            f"{GITHUB_API}{endpoint}",
            headers={
                "Authorization": f"token {token}",
                "Accept": "application/vnd.github.v3+json",
                "X-GitHub-Api-Version": "2022-11-28",
            },
            timeout=30,
        )
        if resp.status_code == 401:
            raise HTTPException(status_code=401, detail="Invalid GitHub token")
        if resp.status_code == 404:
            raise HTTPException(status_code=404, detail="GitHub resource not found")
        resp.raise_for_status()
        return resp.json()


async def github_post(endpoint: str, token: str, payload: dict) -> dict:
    """Make an authenticated POST request to GitHub API."""
    async with httpx.AsyncClient() as client:
        resp = await client.post(
            f"{GITHUB_API}{endpoint}",
            headers={
                "Authorization": f"token {token}",
                "Accept": "application/vnd.github.v3+json",
                "X-GitHub-Api-Version": "2022-11-28",
                "Content-Type": "application/json",
            },
            json=payload,
            timeout=30,
        )
        if resp.status_code == 401:
            raise HTTPException(status_code=401, detail="Invalid GitHub token")
        if resp.status_code == 422:
            detail = resp.json().get("message", "Validation failed")
            raise HTTPException(status_code=422, detail=detail)
        resp.raise_for_status()
        return resp.json()


async def github_put(endpoint: str, token: str, payload: dict) -> dict:
    """Make an authenticated PUT request to GitHub API."""
    async with httpx.AsyncClient() as client:
        resp = await client.put(
            f"{GITHUB_API}{endpoint}",
            headers={
                "Authorization": f"token {token}",
                "Accept": "application/vnd.github.v3+json",
                "X-GitHub-Api-Version": "2022-11-28",
                "Content-Type": "application/json",
            },
            json=payload,
            timeout=30,
        )
        if resp.status_code == 401:
            raise HTTPException(status_code=401, detail="Invalid GitHub token")
        resp.raise_for_status()
        return resp.json()


# ── Routes ───────────────────────────────────────────────────────

@router.post("/verify")
async def verify_github_token(body: GitHubTokenRequest):
    """Verify a GitHub Personal Access Token and return user info."""
    try:
        user = await github_get("/user", body.token)
        repos_data = await github_get("/user/repos?per_page=10&sort=updated", body.token)
        
        return {
            "success": True,
            "user": {
                "login": user.get("login"),
                "name": user.get("name"),
                "email": user.get("email"),
                "avatar_url": user.get("avatar_url"),
                "public_repos": user.get("public_repos", 0),
                "followers": user.get("followers", 0),
                "following": user.get("following", 0),
                "profile_url": user.get("html_url"),
            },
            "recent_repos": [
                {
                    "name": r["name"],
                    "full_name": r["full_name"],
                    "url": r["html_url"],
                    "private": r["private"],
                    "description": r.get("description", ""),
                    "language": r.get("language"),
                    "updated_at": r["updated_at"],
                    "stars": r["stargazers_count"],
                }
                for r in repos_data[:10]
            ],
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error("github.verify_failed", error=str(e))
        raise HTTPException(status_code=500, detail=f"GitHub API error: {str(e)}")


@router.post("/repos/create")
async def create_repository(body: CreateRepoRequest):
    """Create a new GitHub repository."""
    try:
        repo = await github_post("/user/repos", body.github_token, {
            "name": body.repo_name,
            "description": body.description,
            "private": body.private,
            "auto_init": body.auto_init,
            "gitignore_template": "Python",
        })
        return {
            "success": True,
            "repo": {
                "name": repo["name"],
                "full_name": repo["full_name"],
                "url": repo["html_url"],
                "clone_url": repo["clone_url"],
                "ssh_url": repo["ssh_url"],
                "private": repo["private"],
                "default_branch": repo.get("default_branch", "main"),
            }
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error("github.create_repo_failed", error=str(e))
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/repos/push")
async def push_code_to_repo(body: PushCodeRequest):
    """Push generated code files to a GitHub repository."""
    try:
        # Get the authenticated user info
        user_info = await github_get("/user", body.github_token)
        username = user_info["login"]
        repo_full = f"{username}/{body.repo_name}"
        
        # Check if repo exists, create if not
        try:
            await github_get(f"/repos/{repo_full}", body.github_token)
            logger.info("github.repo_exists", repo=repo_full)
        except HTTPException:
            # Create the repo
            await github_post("/user/repos", body.github_token, {
                "name": body.repo_name,
                "description": body.description,
                "private": body.private,
                "auto_init": True,
            })
            # Small delay for repo to be ready
            import asyncio
            await asyncio.sleep(2)
        
        # Push each file
        pushed_files = []
        failed_files = []
        
        for filename, content in body.files.items():
            try:
                # Check if file exists to get SHA (needed for updates)
                sha = None
                try:
                    existing = await github_get(
                        f"/repos/{repo_full}/contents/{filename}",
                        body.github_token
                    )
                    sha = existing.get("sha")
                except HTTPException:
                    pass  # File doesn't exist yet, that's ok
                
                # Encode content to base64
                content_b64 = base64.b64encode(content.encode()).decode()
                
                payload = {
                    "message": f"🤖 Add {filename} - Generated by OmniForge Nexus",
                    "content": content_b64,
                    "branch": "main",
                }
                if sha:
                    payload["sha"] = sha
                
                await github_put(
                    f"/repos/{repo_full}/contents/{filename}",
                    body.github_token,
                    payload
                )
                pushed_files.append(filename)
            
            except Exception as fe:
                logger.warning("github.file_push_failed", file=filename, error=str(fe))
                failed_files.append(filename)
        
        return {
            "success": True,
            "repo_url": f"https://github.com/{repo_full}",
            "pushed_count": len(pushed_files),
            "failed_count": len(failed_files),
            "pushed_files": pushed_files,
            "failed_files": failed_files,
            "branch": "main",
        }
    
    except HTTPException:
        raise
    except Exception as e:
        logger.error("github.push_failed", error=str(e))
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/deploy/pages")
async def deploy_to_github_pages(body: DeployRequest):
    """Enable GitHub Pages for a repository (for static website deployment)."""
    try:
        user_info = await github_get("/user", body.github_token)
        username = user_info["login"]
        repo_full = f"{username}/{body.repo_name}"
        
        # Enable GitHub Pages
        async with httpx.AsyncClient() as client:
            resp = await client.post(
                f"{GITHUB_API}/repos/{repo_full}/pages",
                headers={
                    "Authorization": f"token {body.github_token}",
                    "Accept": "application/vnd.github.v3+json",
                },
                json={
                    "source": {
                        "branch": body.branch,
                        "path": "/"
                    }
                },
                timeout=30,
            )
            
            if resp.status_code in [201, 409]:  # 409 = already enabled
                pages_url = f"https://{username}.github.io/{body.repo_name}"
                return {
                    "success": True,
                    "pages_url": pages_url,
                    "repo_url": f"https://github.com/{repo_full}",
                    "message": "GitHub Pages deployment initiated",
                }
            else:
                resp.raise_for_status()
    
    except HTTPException:
        raise
    except Exception as e:
        logger.error("github.pages_deploy_failed", error=str(e))
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/repos")
async def list_user_repos(token: str):
    """List all repos for the authenticated user."""
    try:
        repos = await github_get(
            "/user/repos?per_page=50&sort=updated&type=all",
            token
        )
        return {
            "success": True,
            "repos": [
                {
                    "name": r["name"],
                    "full_name": r["full_name"],
                    "url": r["html_url"],
                    "private": r["private"],
                    "description": r.get("description", ""),
                    "language": r.get("language"),
                    "updated_at": r["updated_at"],
                    "stars": r["stargazers_count"],
                    "default_branch": r.get("default_branch", "main"),
                }
                for r in repos
            ]
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
